/*
 **********************************************************************************************************************
 *
 * Copyright (c) ETAS GmbH 2023, all rights reserved.
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************
 
 **********************************************************************************************************************
 Machine Type: MCU_RB_GENERIC
 Generated by MEMMAPGEN 12.2.0  
 **********************************************************************************************************************
*/ 
/* MR12 DIR 4.10 VIOLATION: Memmap file must be included multiple times */
/* MR12 RULE 20.5 VIOLATION: AUTOSAR MemMap concept requires #undef, AUTOSAR MemMap requirements are incompatible to MISRA */ 
#if defined DET_START_SEC_CODE
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef DET_START_SEC_CODE           
#elif defined DET_STOP_SEC_CODE      
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef DET_STOP_SEC_CODE             
#elif defined DET_START_SEC_CONST_UNSPECIFIED
  /* CONST_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CONST_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef DET_START_SEC_CONST_UNSPECIFIED           
#elif defined DET_STOP_SEC_CONST_UNSPECIFIED      
  /* CONST_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CONST_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef DET_STOP_SEC_CONST_UNSPECIFIED             
#elif defined DET_START_SEC_VAR_CLEARED_UNSPECIFIED
  /* VAR_CLEARED_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef DET_START_SEC_VAR_CLEARED_UNSPECIFIED           
#elif defined DET_STOP_SEC_VAR_CLEARED_UNSPECIFIED      
  /* VAR_CLEARED_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef DET_STOP_SEC_VAR_CLEARED_UNSPECIFIED             
#elif defined DET_START_SEC_VAR_INIT_UNSPECIFIED
  /* VAR_INIT_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_INIT_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef DET_START_SEC_VAR_INIT_UNSPECIFIED           
#elif defined DET_STOP_SEC_VAR_INIT_UNSPECIFIED      
  /* VAR_INIT_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef DET_STOP_SEC_VAR_INIT_UNSPECIFIED             
#elif defined Det_START_SEC_CODE
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef Det_START_SEC_CODE           
#elif defined Det_STOP_SEC_CODE      
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef Det_STOP_SEC_CODE             
#else 
#error "Det_MemMap.h, wrong pragma command" 
#endif
