/** @file     Rte_Cbk.h
  *
  * @brief    RTE generated callbacks
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.2.0
  */

#ifndef RTE_CBK_H
#define RTE_CBK_H

#include "Rte_Type.h"
/* ----- RTE Callback functions ----- */

#define RTE_SIG_S_APPLICATIONECU_SG_TESTRESULT_TX_CAN_NETWORK_CHANNEL_CAN_TX_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE) Rte_COMCbk_S_ApplicationECU_SG_TestResult_Tx_Can_Network_Channel_CAN_Tx(void);
#define RTE_SIG_S_APPLICATIONECU_SG_TESTRESULT_TX_CAN_NETWORK_CHANNEL_CAN_TX_STOP_SEC_CODE
#include "Rte_MemMap.h"
#define RTE_SIG_S_TESTECU_SG_TESTCODE_TX_CAN_NETWORK_CHANNEL_CAN_RX_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE) Rte_COMCbk_S_TestECU_SG_TestCode_Tx_Can_Network_Channel_CAN_Rx(void);
#define RTE_SIG_S_TESTECU_SG_TESTCODE_TX_CAN_NETWORK_CHANNEL_CAN_RX_STOP_SEC_CODE
#include "Rte_MemMap.h"

#endif /* !RTE_CBK_H */
