/*******************************************************************************
 * Autogenerated by MCALgen for MCU V3.0.51.35438: Mcu_Irq.c
 *******************************************************************************/

/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Mcu.h" /* [$MCU 213]  */

/* Version checks */
#if (MCU_AR_RELEASE_MAJOR_VERSION != (4U)) || (MCU_AR_RELEASE_MINOR_VERSION != (8U)) || (MCU_AR_RELEASE_REVISION_VERSION != (0U))
 #error "MCU AUTOSAR version in MCU.h does not match 4.8.0"
#endif
#if (MCU_SW_MAJOR_VERSION != (3U)) || (MCU_SW_MINOR_VERSION != (0U)) || (MCU_SW_PATCH_VERSION != (51U))
 #error "MCU software version in MCU.h does not match 3.0.51"
#endif
#if (MCU_VENDOR_ID !=  (11U))
 #error "MCU Vendor ID in MCU.h does not match 11"
#endif
 /* [$MCU 110]  */

/*----------------------------
 * Start of code
 *----------------------------*/
#define MCU_START_SEC_CODE
#include "Mcu_MemMap.h"
/*----------------------------
 * End of code
 *----------------------------*/
#define MCU_STOP_SEC_CODE
#include "Mcu_MemMap.h"


