/*******************************************************************************
 * Autogenerated by MCALgen for MCAL V12.2.0.35287: Can.c
 *******************************************************************************/
 /* [$Satisfies $CAN 1003] */
 /* [$Satisfies $CAN 1004] */
/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Can.h" /* [$CAN 34]  */
#include "Can_Implementation.h"

/* [$CAN 1012] [$CAN 111]  [$CAN 1178] */
/* Version checks */
#if (CAN_AR_RELEASE_MAJOR_VERSION != (4U)) || (CAN_AR_RELEASE_MINOR_VERSION != (8U)) || (CAN_AR_RELEASE_REVISION_VERSION != (0U))
 #error "CAN AUTOSAR version in CAN.h does not match 4.8.0"
#endif
#if (CAN_SW_MAJOR_VERSION != (3U)) || (CAN_SW_MINOR_VERSION != (0U)) || (CAN_SW_PATCH_VERSION != (51U))
 #error "CAN software version in CAN.h does not match 3.0.51"
#endif
#if (CAN_VENDOR_ID !=  (11U))
 #error "CAN Vendor ID in CAN.h does not match 11"
#endif

/* [$CAN 394]  */
/*----------------------------
 * Start of const
 *----------------------------*/
#define CAN_START_SEC_CONST_UNSPECIFIED
#include "Can_MemMap.h"

/*----------------------------
 * End of const
 *----------------------------*/
#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "Can_MemMap.h"

/*----------------------------
 * Start of code
 *----------------------------*/
#define CAN_START_SEC_CODE
#include "Can_MemMap.h"

/******************************************************************************
* Can_Init
******************************************************************************/
void Can_Init(const Can_ConfigType* Config) { /* [$CAN 223] [$CAN21 223] [$CAN 386] [$CAN21 386]*/
  Can_Init_helper(Config);
}

/******************************************************************************
* Can_InitController 4.0.2 support
******************************************************************************/
void Can_InitController(uint8 Controller, const Can_ControllerBaudrateConfigType* Config) { /* [$CAN 1102] */
  Can_InitController_helper(Controller, Config);
}

/******************************************************************************
* Can_GetVersionInfo
******************************************************************************/
#if(CAN_VERSION_INFO_API == STD_ON) /* [$CAN 252]  */
void Can_GetVersionInfo(Std_VersionInfoType* versioninfo) { /* [$CAN 224] [$CAN21 224] [$CAN 386] [$CAN21 386]  */
 Can_GetVersionInfo_helper(versioninfo);
}
#endif


/******************************************************************************
* Can_SetControllerMode
******************************************************************************/
/* [$CAN 1288] */
Std_ReturnType Can_SetControllerMode(uint8 Controller,Can_ControllerStateType  Transition) {
  return Can_SetControllerMode_helper(Controller, Transition, FALSE);
}

/******************************************************************************
* Can_DisableControllerInterrupts
******************************************************************************/
void Can_DisableControllerInterrupts(uint8 Controller) { /* [$CAN 231] [$CAN21 231] */
  Can_DisableControllerInterrupts_helper(Controller);
}

/******************************************************************************
* Can_EnableControllerInterrupts
******************************************************************************/
void Can_EnableControllerInterrupts(uint8 Controller) { /* [$CAN 232] [$CAN21 232] */
  Can_EnableControllerInterrupts_helper(Controller);
}

/******************************************************************************
* Can_CheckWakeup
******************************************************************************/
Std_ReturnType Can_CheckWakeup(uint8 Controller) { /* [$CAN 360] [$CAN21 360] [$CAN 1251] [$CAN 1306] */
  return Can_CheckWakeup_helper(Controller);
}

/******************************************************************************
* Can_Write
******************************************************************************/
 /* [$CAN 1252] */
Std_ReturnType Can_Write(Can_HwHandleType Hth, const Can_PduType* PduInfo) { /* [$CAN 233] [$CAN21 233] */
  return Can_Write_helper(Hth, PduInfo, TRUE, FALSE);
}

/******************************************************************************
* Can_MainFunction_Write
******************************************************************************/
void Can_MainFunction_Write(void) { /* [$CAN 225] [$CAN21 225] */
  Can_MainFunction_Write_helper(FALSE);
}

/******************************************************************************
* Can_MainFunction_Read
******************************************************************************/
void Can_MainFunction_Read(void) { /* [$CAN 226] [$CAN21 226] */
  Can_MainFunction_Read_helper(FALSE);
}

/******************************************************************************
* Can_MainFunction_BusOff
******************************************************************************/
void Can_MainFunction_BusOff(void) { /* [$CAN 227] [$CAN21 227] */
  Can_MainFunction_BusOff_helper(FALSE);
}

/******************************************************************************
* Can_MainFunction_Wakeup
******************************************************************************/
void Can_MainFunction_Wakeup(void) { /* [$CAN 228] [$CAN21 228] */
  Can_MainFunction_Wakeup_helper(FALSE);
}

/******************************************************************************
* Can_MainFunction_Mode
******************************************************************************/
void Can_MainFunction_Mode(void) { /* [$CAN 368] [$CAN21 368] */
  Can_MainFunction_Mode_helper();
}

/* [$CAN 1225] */
/******************************************************************************
* Can_SetBaudrate * AR 4.2.1 specific api
******************************************************************************/
#if(CAN_CHANGE_BAUDRATE_API == STD_ON) /* [$CAN 1221] [$CAN21 9482]  */
Std_ReturnType Can_SetBaudrate(uint8 Controller, const uint16 BaudRateConfigID) { /* [$CAN 1130] [$CAN21 491] */
  return Can_ChangeBaudrate_helper(Controller, BaudRateConfigID, CAN_SETBAUDRATE_API_ID);
}
#endif


/******************************************************************************
* AR 4.3.1 specific api
******************************************************************************/
  void Can_DeInit(void) {  /* [$CAN 1245] [$CAN21 91002] */
    Can_DeInit_helper();
  }

  Std_ReturnType Can_GetControllerErrorState(uint8 ControllerId, Can_ErrorStateType* ErrorStatePtr) { /* [$CAN 1246] [$CAN21 91004] */
    return Can_GetControllerErrorState_helper(ControllerId, ErrorStatePtr); //Can_GetControllerErrorState_helper();
  }

  Std_ReturnType Can_GetControllerMode(uint8 Controller, Can_ControllerStateType* ControllerModePtr) { /* [$CAN 1247] [$CAN21 91014] */
    return Can_GetControllerMode_helper(Controller, ControllerModePtr);
  }

/******************************************************************************
* AR 4.4.0 specific api
******************************************************************************/
  Std_ReturnType Can_GetControllerRxErrorCounter(uint8 ControllerId, uint8* RxErrorCounterPtr) {  /* [$CAN 1371] [$CAN21 511] */
    return Can_GetControllerRxErrorCounter_helper (ControllerId, RxErrorCounterPtr);
  }

  Std_ReturnType Can_GetControllerTxErrorCounter(uint8 ControllerId, uint8* TxErrorCounterPtr) { /* [$CAN 1376] [$CAN21 516] */
    return Can_GetControllerTxErrorCounter_helper(ControllerId, TxErrorCounterPtr);
  }

/******************************************************************************
* AR 4.7.0 specific api
******************************************************************************/
  #if (CAN_GLOBAL_TIME_SUPPORT == STD_ON)
Std_ReturnType Can_GetCurrentTime(uint8 ControllerId, Can_TimeStampType* timeStampPtr) { /* [$CAN21 91026] [$CAN 1381] */
    return Can_GetCurrentTime_helper(ControllerId, timeStampPtr);
  }
#endif /* (CAN_GLOBAL_TIME_SUPPORT == STD_ON) */

  #if (CAN_GLOBAL_TIME_SUPPORT == STD_ON)
Std_ReturnType Can_EnableEgressTimeStamp(Can_HwHandleType Hth) { /* [$CAN21 91025] [$CAN 1386] */
    return Can_EnableEgressTimeStamp_helper(Hth);
  }
#endif /* (CAN_GLOBAL_TIME_SUPPORT == STD_ON) */

  #if (CAN_GLOBAL_TIME_SUPPORT == STD_ON)
Std_ReturnType Can_GetEgressTimeStamp(PduIdType TxPduId, Can_HwHandleType Hth, Can_TimeStampType* timeStampPtr) { /* [$CAN21 91027] [$CAN 1391] */
    return Can_GetEgressTimeStamp_helper(TxPduId, Hth, timeStampPtr);
  }
#endif /* (CAN_GLOBAL_TIME_SUPPORT == STD_ON) */

  #if (CAN_GLOBAL_TIME_SUPPORT == STD_ON)
Std_ReturnType Can_GetIngressTimeStamp(Can_HwHandleType Hrh, Can_TimeStampType* timeStampPtr) { /* [$CAN21 91028] [$CAN 1398] */
    return Can_GetIngressTimeStamp_helper(Hrh, timeStampPtr);
  }
#endif /* (CAN_GLOBAL_TIME_SUPPORT == STD_ON) */

/*----------------------------
 * End of code
 *----------------------------*/
#define CAN_STOP_SEC_CODE
#include "Can_MemMap.h"


