/** @file     MyReceivingSWC_MemMap.h
  *
  * @brief    RTE Sample SWC MemMap file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.2.0
  */

#if defined (START_WITH_IF)
#elif defined(MyReceivingSWC_START_SEC_CODE)
#undef MyReceivingSWC_START_SEC_CODE
#define RTE_START_SEC_APPL_CODE
#elif defined(MyReceivingSWC_STOP_SEC_CODE)
#undef MyReceivingSWC_STOP_SEC_CODE
#define RTE_STOP_SEC_APPL_CODE

#endif /* START_WITH_IF */

#include "Rte_MemMap.h"

