/*******************************************************************************
 * Autogenerated by MCALgen for CAN V3.0.51.35438: Can_Lcfg.c
 *******************************************************************************/
 /* [$Satisfies $CAN 1003] */
 /* [$Satisfies $CAN 1004] */

/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Can.h"

/* [$CAN 1012] [$CAN 111]  */
/* Version checks */
#if (CAN_AR_RELEASE_MAJOR_VERSION != (4U)) || (CAN_AR_RELEASE_MINOR_VERSION != (8U)) || (CAN_AR_RELEASE_REVISION_VERSION != (0U))
 #error "CAN AUTOSAR version in CAN.h does not match 4.8.0"
#endif
#if (CAN_SW_MAJOR_VERSION != (3U)) || (CAN_SW_MINOR_VERSION != (0U)) || (CAN_SW_PATCH_VERSION != (51U))
 #error "CAN software version in CAN.h does not match 3.0.51"
#endif
#if (CAN_VENDOR_ID !=  (11U))
 #error "CAN Vendor ID in CAN.h does not match 11"
#endif

/*----------------------------
 * Start of const
 *----------------------------*/
#define CAN_START_SEC_CONST_UNSPECIFIED
#include "Can_MemMap.h"
/*----------------------------
 * End of const
 *----------------------------*/
#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "Can_MemMap.h"

