/*******************************************************************************
 * Autogenerated by MCALgen for MCU V3.0.51.35438: Mcu_Lcfg.c
 *******************************************************************************/

/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Mcu.h"
#include "Mcu_Cbk.h" /* [$MCU 216]  */

/* Version checks */
#if (MCU_AR_RELEASE_MAJOR_VERSION != (4U)) || (MCU_AR_RELEASE_MINOR_VERSION != (8U)) || (MCU_AR_RELEASE_REVISION_VERSION != (0U))
 #error "MCU AUTOSAR version in MCU.h does not match 4.8.0"
#endif
#if (MCU_SW_MAJOR_VERSION != (3U)) || (MCU_SW_MINOR_VERSION != (0U)) || (MCU_SW_PATCH_VERSION != (51U))
 #error "MCU software version in MCU.h does not match 3.0.51"
#endif
#if (MCU_VENDOR_ID !=  (11U))
 #error "MCU Vendor ID in MCU.h does not match 11"
#endif
 /* [$MCU 110]  */

#if (MCU_DEV_ERROR_DETECT == STD_ON)
 #include "Det.h"
#endif

/*----------------------------
 * Start of const
 *----------------------------*/
#define MCU_START_SEC_CONST_UNSPECIFIED
#include "Mcu_MemMap.h"
/*----------------------------
 * End of const
 *----------------------------*/
#define MCU_STOP_SEC_CONST_UNSPECIFIED
#include "Mcu_MemMap.h"


