/*
 **********************************************************************************************************************
 *
 * COPYRIGHT (c) ETAS GmbH 2024, all rights reserved
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************
*/

#if !defined(COM_CFG_CBK_H)
#define COM_CFG_CBK_H

/*
 **********************************************************************************************************************
 * Includes
 **********************************************************************************************************************
*/

#include "ComStack_Types.h"
/* If "Rte_Cbk.h" header file is not generated by RTE in project, either
- use the empty template header(Rte_Cbk.h_tpl) provided in Com component and 
    register it as "Rte_Cbk.h" in project.
- OR if possible disable "ecuC.ecuCRbSettings.ecuCRbRteInUse" switch */
#include "Rte_Cbk.h"

/* no ComUserCbkHeaderFile(s)[ComGeneral] */

/* no ComUserHeaderInclude(s)[ComConfig-ComUserModule-ComUserModuleCnfRef-ComUserModuleCnf] */


/*
 **********************************************************************************************************************
 * Defines/Macros
 **********************************************************************************************************************
*/
/* #define COM_RxIPduTimeoutNotify */

/* #define  COM_RxUpdateTimeoutNotify */

#define COM_RxSignalNotify

/* #define COM_RxSignalGrpNotify */

/* #define COM_TxIPduNotification */

/* #define COM_ERRORNOTIFICATION */

/* #define COM_TxIPduTimeOutNotify */

/* #define COM_CALLBACK_TX */

/* #define COM_CALLBACK_RX */

/* no ComUserCallbackName */


/*
 **********************************************************************************************************************
 * Type definitions
 **********************************************************************************************************************
*/
typedef struct
{
    void (*userCbk_pfct)(CbkHandleIdType id_uo);

} Com_Prv_UserCbk_tst;

typedef uint8 Com_IdxCbk_tuo;


/*
 **********************************************************************************************************************
 * Extern declarations
 **********************************************************************************************************************
*/

#define COM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Com_MemMap.h"

extern const Com_Prv_UserCbk_tst Com_Prv_UserCbk_acst[];

#define COM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Com_MemMap.h"

#define COM_START_SEC_CODE
#include "Com_MemMap.h"

#ifdef COM_TxIPduNotification
#define Com_TxNotify_Wrap_IP_ApplicationECU_To_TestECU_Can_Network_Channel_CAN_Tx (NULL_PTR)
#endif /* end of COM_TxIPduNotification */

#ifdef COM_ERRORNOTIFICATION
#define Com_TxErrNotify_Wrap_IP_ApplicationECU_To_TestECU_Can_Network_Channel_CAN_Tx (NULL_PTR)
#endif /* end of COM_ERRORNOTIFICATION */

#ifdef COM_TxIPduTimeOutNotify
#define Com_TxTONotify_Wrap_IP_ApplicationECU_To_TestECU_Can_Network_Channel_CAN_Tx (NULL_PTR)
#endif /* end of COM_TxIPduTimeOutNotify */

#ifdef COM_RxIPduTimeoutNotify
#define Com_RxTONotify_Wrap_IP_TestECU_To_ApplicationECU_Can_Network_Channel_CAN_Rx (NULL_PTR)
#endif /* end of COM_RxIPduTimeoutNotify */


#define COM_STOP_SEC_CODE
#include "Com_MemMap.h"

#endif  /* end of COM_CFG_CBK_H */


