/** @file     Rte.c
  *
  * @brief    RTE data structures
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.2.0
  *
  * @date     Thu Feb  8 15:40:06 2024
  */

/* RTE_HEADER_START */

#define RTE_CORE

#ifdef RTE_PREINCLUDE
#include RTE_PREINCLUDE
#endif
/* Box: RTE: OS Headers begin */
#include "Rte_Const.h"
#include "Os.h"
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
/* Box: RTE: OS Headers end */
/* Box: RTE headers begin */
#include <Rte.h>
#include <Rte_Intl.h>
#include <Rte_Main.h>
#include "Rte_Type.h"
#include "Rte_Cfg.h"
#include "Rte_Cbk.h"
#if defined(RTE_REQUIRES_COM)
#include <Com.h>
#endif /* defined(RTE_REQUIRES_COM) */
#if defined(RTE_REQUIRES_NVM)
#include <NvM.h>
#ifndef RTE_NVM_VERSION_OVERRIDE
#define RTE_NVM_VERSION_OVERRIDE (0)
#endif /* !RTE_NVM_VERSION_OVERRIDE */
#if ( ( ( NVM_AR_RELEASE_MAJOR_VERSION < 4 ) || ( ( NVM_AR_RELEASE_MAJOR_VERSION == 4 ) && ( NVM_AR_RELEASE_MINOR_VERSION <= 3 ) ) ) && ( RTE_NVM_VERSION_OVERRIDE == 0 ) )
#define RTE_LEGACY_NVM_SUPPORT
#endif /* ( ( ( NVM_AR_RELEASE_MAJOR_VERSION < 4 ) || ( ( NVM_AR_RELEASE_MAJOR_VERSION == 4 ) && ( NVM_AR_RELEASE_MINOR_VERSION <= 3 ) ) ) && ( RTE_NVM_VERSION_OVERRIDE == 0 ) ) */
#endif /* defined(RTE_REQUIRES_NVM) */
#include "Rte_BswM.h"
#include "Rte_ComM.h"
#include "Rte_Det.h"
#include "Rte_EcuM.h"
#include "Rte_MySWC.h"
#include "Rte_rba_DiagLib.h"
#include "SchM_Bfx.h"
#include "SchM_BswM.h"
#include "SchM_Can.h"
#include "SchM_CanIf.h"
#include "SchM_CanSM.h"
#include "SchM_Com.h"
#include "SchM_ComM.h"
#include "SchM_EcuM.h"
#include "SchM_PduR.h"
/* Box: RTE headers end */
/* RTE_HEADER_END */

/* ----- Function prototypes ----- */

/* EXTERN_FN_PROTOTYPES_START */


/* EXTERN_FN_PROTOTYPES_END */

/* RTE_FN_PROTOTYPES_START */

/* Global functions */
/* Instance: /AUTOSAR_Bfx/BswImplementations/Bfx (BSWImpl6_Bfx), Type: Bfx */
#define RTE_BSWM_START_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /AUTOSAR_BswM/BswImplementations/BSWIMPL_BswM (BSWImpl0_BSWIMPL_BswM), Type: BswM */
FUNC(uint8, RTE_CODE) SchM_Mode_BswM_MDGR_BswM_MRP_BswM_MDG(void);
FUNC(Std_ReturnType, RTE_CODE) SchM_Switch_BswM_MDGP_ModeDeclarationGroups_MDG_ECUM_STATE(VAR(uint8, AUTOMATIC) data);
#define RTE_BSWM_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /AUTOSAR_Can/BswImplementations/BSWIMPL_Can (BSWImpl5_BSWIMPL_Can), Type: Can */
/* Instance: /AUTOSAR_CanIf/BswImplementations/CanIf (BSWImpl7_CanIf), Type: CanIf */
/* Instance: /AUTOSAR_CanSM/BswImplementations/CanSM (BSWImpl4_CanSM), Type: CanSM */
/* Instance: /AUTOSAR_Com/BswImplementations/Com (BSWImpl2_Com), Type: Com */
/* Instance: /AUTOSAR_ComM/BswImplementations/ComM (BSWImpl3_ComM), Type: ComM */
/* Instance: /AUTOSAR_EcuM/BswImplementations/EcuM (BSWImpl1_EcuM), Type: EcuM */
/* Instance: /AUTOSAR_PduR/BswImplementations/PduR (BSWImpl8_PduR), Type: PduR */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_BswM (SWCI1), Type: BswM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_ComM (SWCI2), Type: ComM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_Det (SWCI3), Type: Det */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_EcuM (SWCI4), Type: EcuM */
#define RTE_MYSWC_START_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MySWC_ApplicationECU (CPT_MySWC_ApplicationECU), Type: MySWC */
FUNC(Std_ReturnType, RTE_CODE) Rte_Write_CPT_MySWC_ApplicationECU_PPortPrototype_0_DE_MyDataElement(VAR(uint8, AUTOMATIC) data);
#define RTE_MYSWC_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_rba_DiagLib (SWCI5), Type: rba_DiagLib */

/* RTE_FN_PROTOTYPES_END */

/* ----- External variables ----- */

/* RTE_IMPORTS_START */

/* RTE_IMPORTS_END */

/* ----- Global variables ----- */

/* RTE_GLOBALS_START */

#define RTE_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
VAR(Rte_ImplicitBufsType, RTE_DATA) Rte_ImplicitBufs;
#define RTE_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define RTE_START_SEC_VAR_INIT_8
#include "Rte_MemMap.h"
VAR(uint8, RTE_DATA) Rte_ModeCurrent_0 = 4;
VAR(uint8, RTE_DATA) Rte_ModeSchMNext_0 = 6;
#define RTE_STOP_SEC_VAR_INIT_8
#include "Rte_MemMap.h"

#define RTE_OSTASK_BSW_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
VAR(uint8, RTE_DATA) Rte_RECount_OsTask_BSW_divby10_0 = 0;
#define RTE_OSTASK_BSW_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define RTE_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
VAR(uint8, RTE_DATA) Rte_Rx_000000;
#define RTE_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
#if ( defined(RTE_WOWP_EVENTS) && ( RTE_WOWP_EVENTS > 0 ) )
CONST(Rte_TaskInfo, RTE_CONST) Rte_Tasks[2] = {
   { RTE_REF_FROM_TASK(OsTask_BSW), RTE_NUM_TIMEOUT_ALARMS, 0 },
   { RTE_REF_FROM_TASK(OsTask_ASW), RTE_NUM_TIMEOUT_ALARMS, 0 }
};
#endif /* ( defined(RTE_WOWP_EVENTS) && ( RTE_WOWP_EVENTS > 0 ) ) */
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
/* RTE_GLOBALS_END */


/* ----- Data structures ----- */

/* RTE_CDS_START */

/* Instance: /AUTOSAR_Bfx/BswImplementations/Bfx (BSWImpl6_Bfx), Type: Bfx */
/* Omitted for BSW */
/* Instance: /AUTOSAR_BswM/BswImplementations/BSWIMPL_BswM (BSWImpl0_BSWIMPL_BswM), Type: BswM */
/* Omitted for BSW */
/* Instance: /AUTOSAR_Can/BswImplementations/BSWIMPL_Can (BSWImpl5_BSWIMPL_Can), Type: Can */
/* Omitted for BSW */
/* Instance: /AUTOSAR_CanIf/BswImplementations/CanIf (BSWImpl7_CanIf), Type: CanIf */
/* Omitted for BSW */
/* Instance: /AUTOSAR_CanSM/BswImplementations/CanSM (BSWImpl4_CanSM), Type: CanSM */
/* Omitted for BSW */
/* Instance: /AUTOSAR_Com/BswImplementations/Com (BSWImpl2_Com), Type: Com */
/* Omitted for BSW */
/* Instance: /AUTOSAR_ComM/BswImplementations/ComM (BSWImpl3_ComM), Type: ComM */
/* Omitted for BSW */
/* Instance: /AUTOSAR_EcuM/BswImplementations/EcuM (BSWImpl1_EcuM), Type: EcuM */
/* Omitted for BSW */
/* Instance: /AUTOSAR_PduR/BswImplementations/PduR (BSWImpl8_PduR), Type: PduR */
/* Omitted for BSW */
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_BswM (SWCI1), Type: BswM */
CONST(struct Rte_CDS_BswM, RTE_CONST) Rte_Inst_BswM = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_BswM, RTE_CONST) Rte_Self_SWCI1 = &Rte_Inst_BswM;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_ComM (SWCI2), Type: ComM */
CONST(struct Rte_CDS_ComM, RTE_CONST) Rte_Inst_ComM = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_ComM, RTE_CONST) Rte_Self_SWCI2 = &Rte_Inst_ComM;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_Det (SWCI3), Type: Det */
CONST(struct Rte_CDS_Det, RTE_CONST) Rte_Inst_Det = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_Det, RTE_CONST) Rte_Self_SWCI3 = &Rte_Inst_Det;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_EcuM (SWCI4), Type: EcuM */
CONST(struct Rte_CDS_EcuM, RTE_CONST) Rte_Inst_EcuM = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_EcuM, RTE_CONST) Rte_Self_SWCI4 = &Rte_Inst_EcuM;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MySWC_ApplicationECU (CPT_MySWC_ApplicationECU), Type: MySWC */
CONST(struct Rte_CDS_MySWC, RTE_CONST) Rte_Instance_CPT_MySWC_ApplicationECU = {
   /* Data handles */
   &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW.rbuf0,     /* RE_MySWC_RPortPrototype_0_DE_MyDataElement */
   /* Port Data Structure Arrays */
   {
      {
         &Rte_Write_CPT_MySWC_ApplicationECU_PPortPrototype_0_DE_MyDataElement  /* Write_DE_MyDataElement */
      }                                              /* PPortPrototype_0 = PPortPrototype_0[0] */
   },                                                /* PPortPrototype_0 */
   {
      {
         0U                                          /* Rte_Dummy */
      }                                              /* RPortPrototype_0 = RPortPrototype_0[0] */
   }                                                 /* RPortPrototype_0 */
};
CONST(Rte_SelfType_MySWC, RTE_CONST) Rte_Self_CPT_MySWC_ApplicationECU = &Rte_Instance_CPT_MySWC_ApplicationECU;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_rba_DiagLib (SWCI5), Type: rba_DiagLib */
CONST(struct Rte_CDS_rba_DiagLib, RTE_CONST) Rte_Inst_rba_DiagLib = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_rba_DiagLib, RTE_CONST) Rte_Self_SWCI5 = &Rte_Inst_rba_DiagLib;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"

/* RTE_CDS_END */

/* ----- Function implementations ----- */

/* RTE_FUNCTIONS_START */

/* Instance: /AUTOSAR_Bfx/BswImplementations/Bfx (BSWImpl6_Bfx), Type: Bfx */
/* Instance: /AUTOSAR_BswM/BswImplementations/BSWIMPL_BswM (BSWImpl0_BSWIMPL_BswM), Type: BswM */
#define RTE_BSWM_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(uint8, RTE_CODE)
SchM_Mode_BswM_MDGR_BswM_MRP_BswM_MDG(void) /* 3 */
{
   VAR(uint8, AUTOMATIC) rtn;

   Rte_SuspendAllInterrupts();
   rtn = Rte_ModeCurrent_0;
   Rte_ResumeAllInterrupts();
   return rtn;
}

FUNC(Std_ReturnType, RTE_CODE)
SchM_Switch_BswM_MDGP_ModeDeclarationGroups_MDG_ECUM_STATE(VAR(uint8, AUTOMATIC) data) /* 2 */
{
   VAR(Std_ReturnType, AUTOMATIC) rtn;

   rtn = ((VAR(Std_ReturnType, AUTOMATIC))SCHM_E_OK);
   Rte_SuspendOSInterrupts();

   /* Box: SETUP[Async mode switch] begin */
   Rte_ModeCurrent_0 = 6;
   /* Box: SETUP[Async mode switch] end */
   Rte_ResumeOSInterrupts();

   /* Box: SWITCH[Async mode switch] begin */
   if ( data == 2 )
   {

      BswM_Cfg_DfrdBswNotification_BswM_MRP_BswM_MDG_ECUM_STATE_PREP_SHUTDOWN();


   }
   if ( data == 0 )
   {

      BswM_Cfg_DfrdBswNotification_BswM_MRP_BswM_MDG_ECUM_STATE_APP_POST_RUN();


   }
   if ( data == 1 )
   {

      BswM_Cfg_DfrdBswNotification_BswM_MRP_BswM_MDG_ECUM_STATE_APP_RUN();


   }
   if ( data == 3 )
   {

      BswM_Cfg_DfrdBswNotification_BswM_MRP_BswM_MDG_ECUM_STATE_RUN();


   }
   /* Box: SWITCH[Async mode switch] end */
   /* Box: END[Async mode switch] begin */
   Rte_SuspendOSInterrupts();

   Rte_ModeCurrent_0 = data;
   Rte_ResumeOSInterrupts();

   /* Box: END[Async mode switch] end */

   return rtn;
}

#define RTE_BSWM_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /AUTOSAR_Can/BswImplementations/BSWIMPL_Can (BSWImpl5_BSWIMPL_Can), Type: Can */
/* Direct API 'SchM_Enter_Can_CAN_EXCLUSIVE_AREA_00' for 'BSWImpl5_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Enter_Can_CAN_EXCLUSIVE_AREA_00 omitted -- not used */

/* Direct API 'SchM_Enter_Can_CAN_EXCLUSIVE_AREA_01' for 'BSWImpl5_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Enter_Can_CAN_EXCLUSIVE_AREA_01 omitted -- not used */

/* Direct API 'SchM_Enter_Can_CAN_EXCLUSIVE_AREA_02' for 'BSWImpl5_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Enter_Can_CAN_EXCLUSIVE_AREA_02 omitted -- not used */

/* Direct API 'SchM_Exit_Can_CAN_EXCLUSIVE_AREA_00' for 'BSWImpl5_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Exit_Can_CAN_EXCLUSIVE_AREA_00 omitted -- not used */

/* Direct API 'SchM_Exit_Can_CAN_EXCLUSIVE_AREA_01' for 'BSWImpl5_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Exit_Can_CAN_EXCLUSIVE_AREA_01 omitted -- not used */

/* Direct API 'SchM_Exit_Can_CAN_EXCLUSIVE_AREA_02' for 'BSWImpl5_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Exit_Can_CAN_EXCLUSIVE_AREA_02 omitted -- not used */

/* Instance: /AUTOSAR_CanIf/BswImplementations/CanIf (BSWImpl7_CanIf), Type: CanIf */
/* Instance: /AUTOSAR_CanSM/BswImplementations/CanSM (BSWImpl4_CanSM), Type: CanSM */
/* Instance: /AUTOSAR_Com/BswImplementations/Com (BSWImpl2_Com), Type: Com */
/* Instance: /AUTOSAR_ComM/BswImplementations/ComM (BSWImpl3_ComM), Type: ComM */
/* Instance: /AUTOSAR_EcuM/BswImplementations/EcuM (BSWImpl1_EcuM), Type: EcuM */
/* Instance: /AUTOSAR_PduR/BswImplementations/PduR (BSWImpl8_PduR), Type: PduR */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_BswM (SWCI1), Type: BswM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_ComM (SWCI2), Type: ComM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_Det (SWCI3), Type: Det */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_EcuM (SWCI4), Type: EcuM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MySWC_ApplicationECU (CPT_MySWC_ApplicationECU), Type: MySWC */
/* Direct API 'Rte_IReadRef_RE_MySWC_RPortPrototype_0_DE_MyDataElement' for 'CPT_MySWC_ApplicationECU' optimized to implicit read. */
/* No function body generated - API implemented as macro. */
/* Function definition Rte_IReadRef_CPT_MySWC_ApplicationECU_RE_MySWC_RPortPrototype_0_DE_MyDataElement omitted -- not used */

/* Direct API 'Rte_IRead_RE_MySWC_RPortPrototype_0_DE_MyDataElement' for 'CPT_MySWC_ApplicationECU' optimized to implicit read. */
/* No function body generated - API implemented as macro. */
/* Function definition Rte_IRead_CPT_MySWC_ApplicationECU_RE_MySWC_RPortPrototype_0_DE_MyDataElement omitted -- not used */

#define RTE_MYSWC_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(Std_ReturnType, RTE_CODE)
Rte_Write_CPT_MySWC_ApplicationECU_PPortPrototype_0_DE_MyDataElement(VAR(uint8, AUTOMATIC) data) /* 3 */
{
   VAR(Std_ReturnType, AUTOMATIC) rtn = RTE_E_OK;

   /* The signal is ApplicationECU_To_TestECU_Data */
   if ( ((VAR(StatusType, AUTOMATIC))E_OK) != Com_SendSignal(((VAR(Com_SignalIdType, AUTOMATIC))ComConf_ComSignal_S_ApplicationECU_To_TestECU_Data_Can_Network_Channel_CAN_Tx), &data) )
   {
      rtn = ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_COM_STOPPED);
   }

   /* Send complete */
   return rtn;
}

#define RTE_MYSWC_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_rba_DiagLib (SWCI5), Type: rba_DiagLib */
/* ----- API functions ----- */

#define RTE_SIG_S_TESTECU_TO_APPLICATIONECU_DATA_CAN_NETWORK_CHANNEL_CAN_RX_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE)
Rte_COMCbk_S_TestECU_To_ApplicationECU_Data_Can_Network_Channel_CAN_Rx(void)
{
   StatusType comstatus;
   uint8 data;
   boolean read_ok = TRUE;

   /* Box: test begin */
#if !defined(RTE_OMIT_UNINIT_CHECK)
   if ( TRUE != Rte_Initialized )
   {
      return;
   }
#endif /* !defined(RTE_OMIT_UNINIT_CHECK) */
   /* Box: test end */
   /* Box: initialize begin */
   /* Box: initialize end */
   /* Box: receive begin */
   comstatus = Com_ReceiveSignal(((VAR(Com_SignalIdType, AUTOMATIC))ComConf_ComSignal_S_TestECU_To_ApplicationECU_Data_Can_Network_Channel_CAN_Rx), &data);
   if ( ((VAR(StatusType, AUTOMATIC))E_OK) != comstatus )
   {
      read_ok = ((VAR(boolean, AUTOMATIC))FALSE);
   }

   /* Box: receive end */
   /* Box: process begin */
   if ( TRUE == read_ok )
   {
      /* Optimizer: Removed resource lock */
      Rte_Rx_000000 = data;

   }
   /* Box: process end */
}

#define RTE_SIG_S_TESTECU_TO_APPLICATIONECU_DATA_CAN_NETWORK_CHANNEL_CAN_RX_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* RTE_FUNCTIONS_END */

/* ----- Task Bodies ----- */

/* RTE_TASKBODIES_START */

#define OS_START_SEC_CODE_OSTASK_ASW
#include "Os_MemMap.h"
TASK(OsTask_ASW)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   Rte_SuspendAllInterrupts();
   Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW.rbuf0.value = Rte_Rx_000000;
   Rte_ResumeAllInterrupts();
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_MySWC_ApplicationECU begin */
      RE_MySWC_func(Rte_Self_CPT_MySWC_ApplicationECU);
      /* Box: CPT_MySWC_ApplicationECU end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* OsTask_ASW */
#define OS_STOP_SEC_CODE_OSTASK_ASW
#include "Os_MemMap.h"

#define OS_START_SEC_CODE_OSTASK_BSW
#include "Os_MemMap.h"
TASK(OsTask_BSW)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   /* Box: BSWImpl0_BSWIMPL_BswM begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      BswM_MainFunction();
   }
   /* Box: BSWImpl0_BSWIMPL_BswM end */
   /* Box: BSWImpl1_EcuM begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      EcuM_MainFunction();
   }
   /* Box: BSWImpl1_EcuM end */
   /* Box: BSWImpl2_Com begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      Com_MainFunctionRx_ComMainFunctionRx();
   }
   /* Box: BSWImpl2_Com end */
   /* Box: BSWImpl2_Com begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      Com_MainFunctionTx_ComMainFunctionTx();
   }
   /* Box: BSWImpl2_Com end */
   /* Box: BSWImpl3_ComM begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      ComM_MainFunction_Can_Network_Channel_Can_Network();
   }
   /* Box: BSWImpl3_ComM end */
   /* Box: BSWImpl4_CanSM begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      CanSM_MainFunction();
   }
   /* Box: BSWImpl4_CanSM end */
   {
      /* Box: BSWImpl5_BSWIMPL_Can begin */
      Can_MainFunction_Mode();
      /* Box: BSWImpl5_BSWIMPL_Can end */
   }
   {
      /* Box: BSWImpl5_BSWIMPL_Can begin */
      Can_MainFunction_Read();
      /* Box: BSWImpl5_BSWIMPL_Can end */
   }
   {
      /* Box: BSWImpl5_BSWIMPL_Can begin */
      Can_MainFunction_BusOff();
      /* Box: BSWImpl5_BSWIMPL_Can end */
   }
   {
      /* Box: BSWImpl5_BSWIMPL_Can begin */
      Can_MainFunction_Write();
      /* Box: BSWImpl5_BSWIMPL_Can end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   if ( Rte_RECount_OsTask_BSW_divby10_0 != ((VAR(uint8, AUTOMATIC))0U) )
   {
      Rte_RECount_OsTask_BSW_divby10_0--;
   }
   else
   {
      Rte_RECount_OsTask_BSW_divby10_0 = ((VAR(uint8, AUTOMATIC))9);
   }
   TerminateTask();
} /* OsTask_BSW */
#define OS_STOP_SEC_CODE_OSTASK_BSW
#include "Os_MemMap.h"

/* RTE_TASKBODIES_END */

