/*
 **********************************************************************************************************************
 *
 * COPYRIGHT (c) ETAS GmbH 2014, all rights reserved
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************
*/


/*
 ***************************************************************************************************
 * Includes
 ***************************************************************************************************
 */

#include "ComM_Priv.h"

/*
 ***************************************************************************************************
 * Defines
 ***************************************************************************************************
 */
/*
 ***************************************************************************************************
 * Type definitions
 ***************************************************************************************************
 */

/*
 ***************************************************************************************************
 * Variables
 ***************************************************************************************************
 */

#if (COMM_PREVENT_WAKEUP_ENABLED != STD_OFF)

#define COMM_START_SEC_CODE
#include "ComM_MemMap.h"


/*******************************************************************************
 * Function name    : ComM_PreventWakeUp
 * Syntax           : Std_ReturnType ComM_PreventWakeUp( NetworkHandleType Channel, boolean Status )
 * Description      : API to request or release buswake up inhibition for a channel
 * Parameters       : Channel-> The Network Channel for the requested state of ComM state machine.
 *                    Status-> Desired state of wakeup inhibition.
 * Return value     : E_OK: Successfully changed wake up status for the channel
 *                    E_NOT_OK: Changed of wake up status for the channel failed
 *                    COMM_E_UNINIT: ComM not initialized
 ******************************************************************************/
/* MR12 RULE 8.3 VIOLATION:Two declarations exists for this api. One is in ComM.h & another generated by RTE.
 * Hence,the difference in identifiers.*/
Std_ReturnType ComM_PreventWakeUp(NetworkHandleType Channel, boolean Status)
{
    /* Local Variables Declaration */
    ComM_ChannelVarType_tst * channelRamPtr_pst;
    ComM_GlobalVarType_tst *    globalRamPtr_pst;

    /* Local variable initialization */
    channelRamPtr_pst = &ComM_ChannelStruct[Channel];
    globalRamPtr_pst = &ComM_GlobalStruct;

    /************************************DET CHECK STARTS HERE*********************************/
    /* Check for ComM Initialized */
    if (ComM_GlobalStruct.ComM_InitStatus_en != COMM_INIT)
    {
        COMM_DET_REPORT_ERROR(COMM_PREVENT_WAKEUP_APIID, COMM_E_NOT_INITED);
        return COMM_E_NOT_INITIALIZED;
    }

    /* Check if the channel passed is valid */
    if (Channel >= COMM_NO_OF_CHANNELS)
    {
        COMM_DET_REPORT_ERROR(COMM_PREVENT_WAKEUP_APIID, COMM_E_WRONG_PARAMETERS);
        return E_NOT_OK;
    }
    /************************************DET CHECK ENDS HERE**********************************/

    /* When ComMEcuGroupClassification is not set, the PreventWakeup request for the channel is not processed and
    returns E_NOT_OK to indicate to the user that ComMEcuGroupClassification is not set
    in the configuration */
    if((COMM_GET_PREVENT_WAKEUP(globalRamPtr_pst->ComM_EcuGroupClassification_u8) == FALSE))
    {
        return E_NOT_OK;
    }

    /* Update the channel's inhibition status, this update is done irrespective of ECUGroupClassification,
    * But, while processing this in Main function ECUGroupClassification is considered */

    if((COMM_GET_PREVENT_WAKEUP((channelRamPtr_pst->InhibitionReqStatus_u8))) != Status)
    {
        SchM_Enter_ComM_Limitation();

        if(Status != FALSE)
        {
            COMM_SET_PREVENT_WAKEUP((channelRamPtr_pst->InhibitionReqStatus_u8));
        }
        else
        {
            COMM_CLR_PREVENT_WAKEUP((channelRamPtr_pst->InhibitionReqStatus_u8));
        }

        /* For all users and PNC's of the channel, evaluate the Wakeup inhibition counter */
        ComM_Prv_TranslateInhibitionStatus(Channel,COMM_PREVENTWAKEUP,Status);

        SchM_Exit_ComM_Limitation();
    }
    return E_OK;
}

#define COMM_STOP_SEC_CODE
#include "ComM_MemMap.h"

#endif  /*  (COMM_PREVENT_WAKEUP_ENABLED != STD_OFF)  */

