/*******************************************************************************
 * Autogenerated by MCALgen for CAN V3.0.51.35438: Can_PBcfg.h
 *******************************************************************************/
#ifndef CAN_PBCFG_H_
#define CAN_PBCFG_H_

#include "Can.h"

/* [$CAN 443] [$CAN21 443] */


#endif /* CAN_PBCFG_H_ */

