/** @file     Rte.c
  *
  * @brief    RTE data structures
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.2.0
  */

/* RTE_HEADER_START */

#define RTE_CORE

#ifdef RTE_PREINCLUDE
#include RTE_PREINCLUDE
#endif
/* Box: RTE: OS Headers begin */
#include "Rte_Const.h"
#include "Os.h"
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
/* Box: RTE: OS Headers end */
/* Box: RTE headers begin */
#include <Rte.h>
#include <Rte_Intl.h>
#include <Rte_Main.h>
#include "Rte_Type.h"
#include "Rte_Cfg.h"
#include "Rte_Cbk.h"
#if defined(RTE_REQUIRES_COM)
#include <Com.h>
#endif /* defined(RTE_REQUIRES_COM) */
#if defined(RTE_REQUIRES_NVM)
#include <NvM.h>
#ifndef RTE_NVM_VERSION_OVERRIDE
#define RTE_NVM_VERSION_OVERRIDE (0)
#endif /* !RTE_NVM_VERSION_OVERRIDE */
#if ( ( ( NVM_AR_RELEASE_MAJOR_VERSION < 4 ) || ( ( NVM_AR_RELEASE_MAJOR_VERSION == 4 ) && ( NVM_AR_RELEASE_MINOR_VERSION <= 3 ) ) ) && ( RTE_NVM_VERSION_OVERRIDE == 0 ) )
#define RTE_LEGACY_NVM_SUPPORT
#endif /* ( ( ( NVM_AR_RELEASE_MAJOR_VERSION < 4 ) || ( ( NVM_AR_RELEASE_MAJOR_VERSION == 4 ) && ( NVM_AR_RELEASE_MINOR_VERSION <= 3 ) ) ) && ( RTE_NVM_VERSION_OVERRIDE == 0 ) ) */
#endif /* defined(RTE_REQUIRES_NVM) */
#include "Rte_BswM.h"
#include "Rte_ComM.h"
#include "Rte_EcuM.h"
#include "Rte_MyReceivingSWC.h"
#include "Rte_MyTransmittingSWC.h"
#include "Rte_NvM.h"
#include "Rte_rba_DiagLib.h"
#include "SchM_BswM.h"
#include "SchM_Can.h"
#include "SchM_CanSM.h"
#include "SchM_Com.h"
#include "SchM_ComM.h"
#include "SchM_EcuM.h"
#include "SchM_MemIf.h"
#include "SchM_NvM.h"
/* Box: RTE headers end */
/* RTE_HEADER_END */

/* ----- Function prototypes ----- */

/* EXTERN_FN_PROTOTYPES_START */


/* EXTERN_FN_PROTOTYPES_END */

/* RTE_FN_PROTOTYPES_START */

/* Global functions */
#define RTE_SYS_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE) SchM_IModeInit(void);
#define RTE_SYS_STOP_SEC_CODE
#include "Rte_MemMap.h"
#define RTE_BSWM_START_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /AUTOSAR_BswM/BswImplementations/BSWIMPL_BswM (BSWImpl3_BSWIMPL_BswM), Type: BswM */
FUNC(uint8, RTE_CODE) SchM_Mode_BswM_MDGR_BswM_MRP_BswM_MDG(void);
/* Instance: /AUTOSAR_Can/BswImplementations/BSWIMPL_Can (BSWImpl1_BSWIMPL_Can), Type: Can */
/* Instance: /AUTOSAR_CanSM/BswImplementations/CanSM (BSWImpl2_CanSM), Type: CanSM */
/* Instance: /AUTOSAR_Com/BswImplementations/Com (BSWImpl5_Com), Type: Com */
/* Instance: /AUTOSAR_ComM/BswImplementations/ComM (BSWImpl0_ComM), Type: ComM */
/* Instance: /AUTOSAR_EcuM/BswImplementations/EcuM (BSWImpl4_EcuM), Type: EcuM */
/* Instance: /AUTOSAR_MemIf/BswImplementations/MemIf (BSWImpl7_MemIf), Type: MemIf */
/* Instance: /AUTOSAR_NvM/BswImplementations/NvM (BSWImpl6_NvM), Type: NvM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_BswM (SWCI4), Type: BswM */
FUNC(uint8, RTE_CODE) Rte_Mode_BswM_RP_BswM_MRP_SwcModeRequest_MDGP_MSI_ShutDown(void);
#define RTE_BSWM_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_ComM (CPT_ComM), Type: ComM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_EcuM (SWCI5), Type: EcuM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MyReceivingSWC_ApplicationEcu (CPT_MyReceivingSWC_ApplicationEcu), Type: MyReceivingSWC */
#define RTE_MYRECEIVINGSWC_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_EraseBlock(void);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_GetDataIndex(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataIndexPtr);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_GetErrorStatus(P2VAR(NvM_RequestResultType, AUTOMATIC, RTE_APPL_DATA) RequestResultPtr);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_InvalidateNvBlock(void);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_ReadBlock(VAR(NvM_Rb_VoidPtr, AUTOMATIC) DstPtr);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_ReadPRAMBlock(void);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_RestoreBlockDefaults(VAR(NvM_Rb_VoidPtr, AUTOMATIC) DstPtr);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_RestorePRAMBlockDefaults(void);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_SetDataIndex(VAR(uint8, AUTOMATIC) DataIndex);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_SetRamBlockStatus(VAR(boolean, AUTOMATIC) BlockChanged);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_WriteBlock(VAR(NvM_Rb_ConstVoidPtr, AUTOMATIC) SrcPtr);
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_WritePRAMBlock(void);
#define RTE_MYRECEIVINGSWC_STOP_SEC_CODE
#include "Rte_MemMap.h"
#define RTE_MYTRANSMITTINGSWC_START_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MyTransmittingSWC_ApplicationEcu (CPT_MyTransmittingSWC_ApplicationEcu), Type: MyTransmittingSWC */
FUNC(Std_ReturnType, RTE_CODE) Rte_Write_CPT_MyTransmittingSWC_ApplicationEcu_PPortPrototype_0_DE_MyDataElement(VAR(uint8, AUTOMATIC) data);
#define RTE_MYTRANSMITTINGSWC_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_NvM (SWCI6), Type: NvM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_rba_DiagLib (SWCI3), Type: rba_DiagLib */

/* RTE_FN_PROTOTYPES_END */

/* ----- External variables ----- */

/* RTE_IMPORTS_START */

/* RTE_IMPORTS_END */

/* ----- Global variables ----- */

/* RTE_GLOBALS_START */

#define RTE_START_SEC_VAR_INIT_UNSPECIFIED
#include "Rte_MemMap.h"
VAR(Rte_PimType_MyReceivingSWC_boolean, RTE_APPL_DATA) Rte_CPim_CPT_MyReceivingSWC_ApplicationEcu_PIM_01 = 0;
VAR(Rte_PimType_MyReceivingSWC_uint8, RTE_APPL_DATA) Rte_CPim_CPT_MyReceivingSWC_ApplicationEcu_PIM_02 = 1;
#define RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "Rte_MemMap.h"

#define RTE_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
VAR(Rte_ImplicitBufsType, RTE_DATA) Rte_ImplicitBufs;
#define RTE_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define RTE_START_SEC_VAR_INIT_8
#include "Rte_MemMap.h"
VAR(uint8, RTE_DATA) Rte_ModeCurrent_0 = 4;
VAR(uint8, RTE_DATA) Rte_ModeCurrent_1 = 4;
VAR(uint8, RTE_DATA) Rte_ModeCurrent_2 = 1;
VAR(uint8, RTE_DATA) Rte_ModeNext_2 = 2;
VAR(uint8, RTE_DATA) Rte_ModeSchMNext_1 = 6;
#define RTE_STOP_SEC_VAR_INIT_8
#include "Rte_MemMap.h"

#define RTE_OSTASK_BSW_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
VAR(uint8, RTE_DATA) Rte_RECount_OsTask_BSW_divby10_0 = 0;
#define RTE_OSTASK_BSW_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define RTE_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
VAR(uint8, RTE_DATA) Rte_Rx_000000;
#define RTE_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
#if ( defined(RTE_WOWP_EVENTS) && ( RTE_WOWP_EVENTS > 0 ) )
CONST(Rte_TaskInfo, RTE_CONST) Rte_Tasks[2] = {
   { RTE_REF_FROM_TASK(OsTask_BSW), RTE_NUM_TIMEOUT_ALARMS, 0 },
   { RTE_REF_FROM_TASK(OsTask_ASW), RTE_NUM_TIMEOUT_ALARMS, 0 }
};
#endif /* ( defined(RTE_WOWP_EVENTS) && ( RTE_WOWP_EVENTS > 0 ) ) */
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
/* RTE_GLOBALS_END */


/* ----- Data structures ----- */

/* RTE_CDS_START */

/* Instance: /AUTOSAR_BswM/BswImplementations/BSWIMPL_BswM (BSWImpl3_BSWIMPL_BswM), Type: BswM */
/* Omitted for BSW */
/* Instance: /AUTOSAR_Can/BswImplementations/BSWIMPL_Can (BSWImpl1_BSWIMPL_Can), Type: Can */
/* Omitted for BSW */
/* Instance: /AUTOSAR_CanSM/BswImplementations/CanSM (BSWImpl2_CanSM), Type: CanSM */
/* Omitted for BSW */
/* Instance: /AUTOSAR_Com/BswImplementations/Com (BSWImpl5_Com), Type: Com */
/* Omitted for BSW */
/* Instance: /AUTOSAR_ComM/BswImplementations/ComM (BSWImpl0_ComM), Type: ComM */
/* Omitted for BSW */
/* Instance: /AUTOSAR_EcuM/BswImplementations/EcuM (BSWImpl4_EcuM), Type: EcuM */
/* Omitted for BSW */
/* Instance: /AUTOSAR_MemIf/BswImplementations/MemIf (BSWImpl7_MemIf), Type: MemIf */
/* Omitted for BSW */
/* Instance: /AUTOSAR_NvM/BswImplementations/NvM (BSWImpl6_NvM), Type: NvM */
/* Omitted for BSW */
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_BswM (SWCI4), Type: BswM */
CONST(struct Rte_CDS_BswM, RTE_CONST) Rte_Inst_BswM = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_BswM, RTE_CONST) Rte_Self_SWCI4 = &Rte_Inst_BswM;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_ComM (CPT_ComM), Type: ComM */
CONST(struct Rte_CDS_ComM, RTE_CONST) Rte_Inst_ComM = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_ComM, RTE_CONST) Rte_Self_CPT_ComM = &Rte_Inst_ComM;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_EcuM (SWCI5), Type: EcuM */
CONST(struct Rte_CDS_EcuM, RTE_CONST) Rte_Inst_EcuM = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_EcuM, RTE_CONST) Rte_Self_SWCI5 = &Rte_Inst_EcuM;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MyReceivingSWC_ApplicationEcu (CPT_MyReceivingSWC_ApplicationEcu), Type: MyReceivingSWC */
CONST(struct Rte_CDS_MyReceivingSWC, RTE_CONST) Rte_Instance_CPT_MyReceivingSWC_ApplicationEcu = {
   /* Data handles */
   &Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW.rbuf0,     /* RE_Rx_RPortPrototype_0_DE_MyDataElement */
   /* Per-Instance Memorys (sic) */
   &Rte_CPim_CPT_MyReceivingSWC_ApplicationEcu_PIM_01,  /* Pim_PIM_01 */
   &Rte_CPim_CPT_MyReceivingSWC_ApplicationEcu_PIM_02,  /* Pim_PIM_02 */
   /* Port Data Structure Arrays */
   {
      {
         0U                                          /* Rte_Dummy */
      }                                              /* RPortPrototype_0 = RPortPrototype_0[0] */
   },                                                /* RPortPrototype_0 */
   {
      {
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_EraseBlock,  /* Call_EraseBlock */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_GetDataIndex,  /* Call_GetDataIndex */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_GetErrorStatus,  /* Call_GetErrorStatus */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_InvalidateNvBlock,  /* Call_InvalidateNvBlock */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_ReadBlock,  /* Call_ReadBlock */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_ReadPRAMBlock,  /* Call_ReadPRAMBlock */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_RestoreBlockDefaults,  /* Call_RestoreBlockDefaults */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_RestorePRAMBlockDefaults,  /* Call_RestorePRAMBlockDefaults */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_SetDataIndex,  /* Call_SetDataIndex */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_SetRamBlockStatus,  /* Call_SetRamBlockStatus */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_WriteBlock,  /* Call_WriteBlock */
         &Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_WritePRAMBlock  /* Call_WritePRAMBlock */
      }                                              /* R_NvMService_0 = R_NvMService_0[0] */
   }                                                 /* R_NvMService_0 */
};
CONST(Rte_SelfType_MyReceivingSWC, RTE_CONST) Rte_Self_CPT_MyReceivingSWC_ApplicationEcu = &Rte_Instance_CPT_MyReceivingSWC_ApplicationEcu;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MyTransmittingSWC_ApplicationEcu (CPT_MyTransmittingSWC_ApplicationEcu), Type: MyTransmittingSWC */
CONST(struct Rte_CDS_MyTransmittingSWC, RTE_CONST) Rte_Instance_CPT_MyTransmittingSWC_ApplicationEcu = {
   /* Port Data Structure Arrays */
   {
      {
         &Rte_Write_CPT_MyTransmittingSWC_ApplicationEcu_PPortPrototype_0_DE_MyDataElement  /* Write_DE_MyDataElement */
      }                                              /* PPortPrototype_0 = PPortPrototype_0[0] */
   }                                                 /* PPortPrototype_0 */
};
CONST(Rte_SelfType_MyTransmittingSWC, RTE_CONST) Rte_Self_CPT_MyTransmittingSWC_ApplicationEcu = &Rte_Instance_CPT_MyTransmittingSWC_ApplicationEcu;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_NvM (SWCI6), Type: NvM */
CONST(struct Rte_CDS_NvM, RTE_CONST) Rte_Inst_NvM = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_NvM, RTE_CONST) Rte_Self_SWCI6 = &Rte_Inst_NvM;
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_rba_DiagLib (SWCI3), Type: rba_DiagLib */
CONST(struct Rte_CDS_rba_DiagLib, RTE_CONST) Rte_Inst_rba_DiagLib = {
   0U                                                /* Rte_Dummy */
};
CONST(Rte_SelfType_rba_DiagLib, RTE_CONST) Rte_Self_SWCI3 = &Rte_Inst_rba_DiagLib;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "Rte_MemMap.h"

/* RTE_CDS_END */

/* ----- Function implementations ----- */

/* RTE_FUNCTIONS_START */

/* Instance: /AUTOSAR_BswM/BswImplementations/BSWIMPL_BswM (BSWImpl3_BSWIMPL_BswM), Type: BswM */
/* Direct API 'SchM_Switch_BswM_MDGP_AUTOSAR_BswM_ModeDeclarationGroups_MDG_ECUM_STATE' for 'BSWImpl3_BSWIMPL_BswM' optimized to a constant. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Switch_BswM_MDGP_AUTOSAR_BswM_ModeDeclarationGroups_MDG_ECUM_STATE omitted -- not used */

#define RTE_BSWM_START_SEC_CODE
#include "Rte_MemMap.h"
/* Direct API 'SchM_Mode_BswM_MDGR_BswM_MRP_BswM_MDG' for 'BSWImpl3_BSWIMPL_BswM' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(uint8, RTE_CODE)
SchM_Mode_BswM_MDGR_BswM_MRP_BswM_MDG(void) /* 1 */
{
   return 4;
}

#define RTE_BSWM_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /AUTOSAR_Can/BswImplementations/BSWIMPL_Can (BSWImpl1_BSWIMPL_Can), Type: Can */
/* Direct API 'SchM_Enter_Can_CAN_EXCLUSIVE_AREA_00' for 'BSWImpl1_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Enter_Can_CAN_EXCLUSIVE_AREA_00 omitted -- not used */

/* Direct API 'SchM_Enter_Can_CAN_EXCLUSIVE_AREA_01' for 'BSWImpl1_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Enter_Can_CAN_EXCLUSIVE_AREA_01 omitted -- not used */

/* Direct API 'SchM_Enter_Can_CAN_EXCLUSIVE_AREA_02' for 'BSWImpl1_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Enter_Can_CAN_EXCLUSIVE_AREA_02 omitted -- not used */

/* Direct API 'SchM_Exit_Can_CAN_EXCLUSIVE_AREA_00' for 'BSWImpl1_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Exit_Can_CAN_EXCLUSIVE_AREA_00 omitted -- not used */

/* Direct API 'SchM_Exit_Can_CAN_EXCLUSIVE_AREA_01' for 'BSWImpl1_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Exit_Can_CAN_EXCLUSIVE_AREA_01 omitted -- not used */

/* Direct API 'SchM_Exit_Can_CAN_EXCLUSIVE_AREA_02' for 'BSWImpl1_BSWIMPL_Can' optimized to an inline call. */
/* No function body generated - SW-C is delivered as source. */
/* Function definition SchM_Exit_Can_CAN_EXCLUSIVE_AREA_02 omitted -- not used */

/* Instance: /AUTOSAR_CanSM/BswImplementations/CanSM (BSWImpl2_CanSM), Type: CanSM */
/* Instance: /AUTOSAR_Com/BswImplementations/Com (BSWImpl5_Com), Type: Com */
/* Instance: /AUTOSAR_ComM/BswImplementations/ComM (BSWImpl0_ComM), Type: ComM */
/* Instance: /AUTOSAR_EcuM/BswImplementations/EcuM (BSWImpl4_EcuM), Type: EcuM */
/* Instance: /AUTOSAR_MemIf/BswImplementations/MemIf (BSWImpl7_MemIf), Type: MemIf */
/* Instance: /AUTOSAR_NvM/BswImplementations/NvM (BSWImpl6_NvM), Type: NvM */
#define RTE_BSWM_START_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_BswM (SWCI4), Type: BswM */
/* Direct API 'Rte_Mode_RP_BswM_MRP_SwcModeRequest_MDGP_MSI_ShutDown' for 'SWCI4' optimized to a constant. */
/* Function body emitted - SW-C is delivered as object-code. */
FUNC(uint8, RTE_CODE)
Rte_Mode_BswM_RP_BswM_MRP_SwcModeRequest_MDGP_MSI_ShutDown(void) /* 1 */
{
   return 1;
}

#define RTE_BSWM_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_ComM (CPT_ComM), Type: ComM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_EcuM (SWCI5), Type: EcuM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MyReceivingSWC_ApplicationEcu (CPT_MyReceivingSWC_ApplicationEcu), Type: MyReceivingSWC */
/* Direct API 'Rte_IReadRef_RE_Rx_RPortPrototype_0_DE_MyDataElement' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to implicit read. */
/* No function body generated - API implemented as macro. */
/* Function definition Rte_IReadRef_CPT_MyReceivingSWC_ApplicationEcu_RE_Rx_RPortPrototype_0_DE_MyDataElement omitted -- not used */

/* Direct API 'Rte_IRead_RE_Rx_RPortPrototype_0_DE_MyDataElement' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to implicit read. */
/* No function body generated - API implemented as macro. */
/* Function definition Rte_IRead_CPT_MyReceivingSWC_ApplicationEcu_RE_Rx_RPortPrototype_0_DE_MyDataElement omitted -- not used */

/* Direct API 'Rte_Pim_PIM_01' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to direct PIM access. */
/* No function body generated - API implemented as macro. */
/* Function definition Rte_Pim_CPT_MyReceivingSWC_ApplicationEcu_PIM_01 omitted -- not used */

/* Direct API 'Rte_Pim_PIM_02' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to direct PIM access. */
/* No function body generated - API implemented as macro. */
/* Function definition Rte_Pim_CPT_MyReceivingSWC_ApplicationEcu_PIM_02 omitted -- not used */

#define RTE_MYRECEIVINGSWC_START_SEC_CODE
#include "Rte_MemMap.h"
/* Direct API 'Rte_Call_R_NvMService_0_EraseBlock' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_EraseBlock(void) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_GetDataIndex' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_GetDataIndex(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataIndexPtr) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_GetErrorStatus' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_GetErrorStatus(P2VAR(NvM_RequestResultType, AUTOMATIC, RTE_APPL_DATA) RequestResultPtr) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_InvalidateNvBlock' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_InvalidateNvBlock(void) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_ReadBlock' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_ReadBlock(VAR(NvM_Rb_VoidPtr, AUTOMATIC) DstPtr) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_ReadPRAMBlock' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_ReadPRAMBlock(void) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_RestoreBlockDefaults' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_RestoreBlockDefaults(VAR(NvM_Rb_VoidPtr, AUTOMATIC) DstPtr) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_RestorePRAMBlockDefaults' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_RestorePRAMBlockDefaults(void) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_SetDataIndex' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_SetDataIndex(VAR(uint8, AUTOMATIC) DataIndex) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_SetRamBlockStatus' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_SetRamBlockStatus(VAR(boolean, AUTOMATIC) BlockChanged) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_WriteBlock' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_WriteBlock(VAR(NvM_Rb_ConstVoidPtr, AUTOMATIC) SrcPtr) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

/* Direct API 'Rte_Call_R_NvMService_0_WritePRAMBlock' for 'CPT_MyReceivingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_CPT_MyReceivingSWC_ApplicationEcu_R_NvMService_0_WritePRAMBlock(void) /* 1 */
{
   return ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_UNCONNECTED);
}

#define RTE_MYRECEIVINGSWC_STOP_SEC_CODE
#include "Rte_MemMap.h"
#define RTE_MYTRANSMITTINGSWC_START_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MyTransmittingSWC_ApplicationEcu (CPT_MyTransmittingSWC_ApplicationEcu), Type: MyTransmittingSWC */
/* Direct API 'Rte_Write_PPortPrototype_0_DE_MyDataElement' for 'CPT_MyTransmittingSWC_ApplicationEcu' optimized to a constant. */
/* Function body emitted to support indirect API */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Write_CPT_MyTransmittingSWC_ApplicationEcu_PPortPrototype_0_DE_MyDataElement(VAR(uint8, AUTOMATIC) data) /* 1 */
{
   VAR(Std_ReturnType, AUTOMATIC) rtn;

   rtn = ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK);
   /* Write suppressed because Sender-Receiver DataItem /Interfaces/My_SR_Interface/DE_MyDataElement in port /MyTransmittingSWC/MyTransmittingSWC/PPortPrototype_0 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_MyTransmittingSWC_ApplicationEcu is unconnected */
   ((void)data);
   /* Send complete */
   return rtn;
}

#define RTE_MYTRANSMITTINGSWC_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_NvM (SWCI6), Type: NvM */
/* Instance: /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_rba_DiagLib (SWCI3), Type: rba_DiagLib */
/* ----- API functions ----- */

#define RTE_SIG_S_APPLICATIONECU_SG_TESTRESULT_TX_CAN_NETWORK_CHANNEL_CAN_TX_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE)
Rte_COMCbk_S_ApplicationECU_SG_TestResult_Tx_Can_Network_Channel_CAN_Tx(void)
{
   StatusType comstatus;
   uint8 data;
   boolean read_ok = TRUE;

   /* Box: test begin */
#if !defined(RTE_OMIT_UNINIT_CHECK)
   if ( TRUE != Rte_Initialized )
   {
      return;
   }
#endif /* !defined(RTE_OMIT_UNINIT_CHECK) */
   /* Box: test end */
   /* Box: initialize begin */
   /* Box: initialize end */
   /* Box: receive begin */
   comstatus = Com_ReceiveSignal(((VAR(Com_SignalIdType, AUTOMATIC))ComConf_ComSignal_S_ApplicationECU_SG_TestResult_Tx_Can_Network_Channel_CAN_Tx), &data);
   if ( ((VAR(StatusType, AUTOMATIC))E_OK) != comstatus )
   {
      read_ok = ((VAR(boolean, AUTOMATIC))FALSE);
   }

   /* Box: receive end */
   /* Box: process begin */
   if ( TRUE == read_ok )
   {
      /* Optimizer: Removed resource lock */
      Rte_Rx_000000 = data;

   }
   /* Box: process end */
}

#define RTE_SIG_S_APPLICATIONECU_SG_TESTRESULT_TX_CAN_NETWORK_CHANNEL_CAN_TX_STOP_SEC_CODE
#include "Rte_MemMap.h"
#define RTE_SIG_S_TESTECU_SG_TESTCODE_TX_CAN_NETWORK_CHANNEL_CAN_RX_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE)
Rte_COMCbk_S_TestECU_SG_TestCode_Tx_Can_Network_Channel_CAN_Rx(void)
{
   StatusType comstatus;
   uint8 data;
   boolean read_ok = TRUE;

   /* Box: test begin */
#if !defined(RTE_OMIT_UNINIT_CHECK)
   if ( TRUE != Rte_Initialized )
   {
      return;
   }
#endif /* !defined(RTE_OMIT_UNINIT_CHECK) */
   /* Box: test end */
   /* Box: initialize begin */
   /* Box: initialize end */
   /* Box: receive begin */
   comstatus = Com_ReceiveSignal(((VAR(Com_SignalIdType, AUTOMATIC))ComConf_ComSignal_S_TestECU_SG_TestCode_Tx_Can_Network_Channel_CAN_Rx), &data);
   if ( ((VAR(StatusType, AUTOMATIC))E_OK) != comstatus )
   {
      read_ok = ((VAR(boolean, AUTOMATIC))FALSE);
   }

   /* Box: receive end */
   /* Box: process begin */
   if ( TRUE == read_ok )
   {
      /* Optimizer: Removed resource lock */
      Rte_Rx_000000 = data;

   }
   /* Box: process end */
}

#define RTE_SIG_S_TESTECU_SG_TESTCODE_TX_CAN_NETWORK_CHANNEL_CAN_RX_STOP_SEC_CODE
#include "Rte_MemMap.h"
#define RTE_SYS_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE)
SchM_IModeInit(void) /* 1 */
{
   /* RE activation */
   {

      BswM_Cfg_ImdtBswNotification_BswM_MRP_BswM_MDG_ECUM_STATE_STARTUP_ONE();


   }
}
#define RTE_SYS_STOP_SEC_CODE
#include "Rte_MemMap.h"
/* RTE_FUNCTIONS_END */

/* ----- Task Bodies ----- */

/* RTE_TASKBODIES_START */

#define OS_START_SEC_CODE_OSTASK_ASW
#include "Os_MemMap.h"
TASK(OsTask_ASW)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   Rte_SuspendAllInterrupts();
   Rte_ImplicitBufs.isa_1.Rte_OsTask_ASW.rbuf0.value = Rte_Rx_000000;
   Rte_ResumeAllInterrupts();
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_MyReceivingSWC_ApplicationEcu begin */
      RE_Rx_func(Rte_Self_CPT_MyReceivingSWC_ApplicationEcu);
      /* Box: CPT_MyReceivingSWC_ApplicationEcu end */
   }
   {
      /* Box: CPT_MyTransmittingSWC_ApplicationEcu begin */
      RE_Tx_func(Rte_Self_CPT_MyTransmittingSWC_ApplicationEcu);
      /* Box: CPT_MyTransmittingSWC_ApplicationEcu end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* OsTask_ASW */
#define OS_STOP_SEC_CODE_OSTASK_ASW
#include "Os_MemMap.h"

#define OS_START_SEC_CODE_OSTASK_BSW
#include "Os_MemMap.h"
TASK(OsTask_BSW)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: BSWImpl6_NvM begin */
      NvM_MainFunction();
      /* Box: BSWImpl6_NvM end */
   }
   {
      /* Box: BSWImpl7_MemIf begin */
      MemIf_Rb_MainFunction();
      /* Box: BSWImpl7_MemIf end */
   }
   /* Box: BSWImpl5_Com begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      Com_MainFunctionTx_ComMainFunctionTx();
   }
   /* Box: BSWImpl5_Com end */
   /* Box: BSWImpl5_Com begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      Com_MainFunctionRx_ComMainFunctionRx();
   }
   /* Box: BSWImpl5_Com end */
   {
      /* Box: BSWImpl1_BSWIMPL_Can begin */
      Can_MainFunction_Read();
      /* Box: BSWImpl1_BSWIMPL_Can end */
   }
   {
      /* Box: BSWImpl1_BSWIMPL_Can begin */
      Can_MainFunction_Mode();
      /* Box: BSWImpl1_BSWIMPL_Can end */
   }
   /* Box: BSWImpl0_ComM begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      ComM_MainFunction_Can_Network_Channel_Can_Network();
   }
   /* Box: BSWImpl0_ComM end */
   {
      /* Box: BSWImpl1_BSWIMPL_Can begin */
      Can_MainFunction_Write();
      /* Box: BSWImpl1_BSWIMPL_Can end */
   }
   /* Box: BSWImpl2_CanSM begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      CanSM_MainFunction();
   }
   /* Box: BSWImpl2_CanSM end */
   /* Box: BSWImpl4_EcuM begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      EcuM_MainFunction();
   }
   /* Box: BSWImpl4_EcuM end */
   /* Box: BSWImpl3_BSWIMPL_BswM begin */
   if ( Rte_RECount_OsTask_BSW_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      BswM_MainFunction();
   }
   /* Box: BSWImpl3_BSWIMPL_BswM end */
   {
      /* Box: BSWImpl1_BSWIMPL_Can begin */
      Can_MainFunction_BusOff();
      /* Box: BSWImpl1_BSWIMPL_Can end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   if ( Rte_RECount_OsTask_BSW_divby10_0 != ((VAR(uint8, AUTOMATIC))0U) )
   {
      Rte_RECount_OsTask_BSW_divby10_0--;
   }
   else
   {
      Rte_RECount_OsTask_BSW_divby10_0 = ((VAR(uint8, AUTOMATIC))9);
   }
   TerminateTask();
} /* OsTask_BSW */
#define OS_STOP_SEC_CODE_OSTASK_BSW
#include "Os_MemMap.h"

/* RTE_TASKBODIES_END */

