/*
 **********************************************************************************************************************
 *
 * Copyright (c) ETAS GmbH 2023, all rights reserved.
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************
 
 **********************************************************************************************************************
 Machine Type: MCU_RB_GENERIC
 Generated by MEMMAPGEN 12.2.0  
 **********************************************************************************************************************
*/ 
/* MR12 DIR 4.10 VIOLATION: Memmap file must be included multiple times */
/* MR12 RULE 20.5 VIOLATION: AUTOSAR MemMap concept requires #undef, AUTOSAR MemMap requirements are incompatible to MISRA */ 
#if defined BSWM_START_SEC_CODE
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_CODE           
#elif defined BSWM_STOP_SEC_CODE      
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_CODE             
#elif defined BSWM_START_SEC_CONFIG_DATA_POSTBUILD_32
  /* CONFIG_DATA_POSTBUILD_32 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CONFIG_DATA_POSTBUILD_32
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_CONFIG_DATA_POSTBUILD_32           
#elif defined BSWM_STOP_SEC_CONFIG_DATA_POSTBUILD_32      
  /* CONFIG_DATA_POSTBUILD_32 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_CONFIG_DATA_POSTBUILD_32             
#elif defined BSWM_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
  /* CONFIG_DATA_POSTBUILD_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED           
#elif defined BSWM_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED      
  /* CONFIG_DATA_POSTBUILD_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED             
#elif defined BSWM_START_SEC_CONST_16
  /* CONST_16 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CONST_16
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_CONST_16           
#elif defined BSWM_STOP_SEC_CONST_16      
  /* CONST_16 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CONST_16
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_CONST_16             
#elif defined BSWM_START_SEC_CONST_8
  /* CONST_8 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CONST_8
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_CONST_8           
#elif defined BSWM_STOP_SEC_CONST_8      
  /* CONST_8 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CONST_8
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_CONST_8             
#elif defined BSWM_START_SEC_CONST_UNSPECIFIED
  /* CONST_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CONST_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_CONST_UNSPECIFIED           
#elif defined BSWM_STOP_SEC_CONST_UNSPECIFIED      
  /* CONST_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CONST_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_CONST_UNSPECIFIED             
#elif defined BSWM_START_SEC_VAR_CLEARED_32
  /* VAR_CLEARED_32 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_CLEARED_32
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_CLEARED_32           
#elif defined BSWM_STOP_SEC_VAR_CLEARED_32      
  /* VAR_CLEARED_32 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_CLEARED_32
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_CLEARED_32             
#elif defined BSWM_START_SEC_VAR_CLEARED_8
  /* VAR_CLEARED_8 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_CLEARED_8
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_CLEARED_8           
#elif defined BSWM_STOP_SEC_VAR_CLEARED_8      
  /* VAR_CLEARED_8 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_CLEARED_8
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_CLEARED_8             
#elif defined BSWM_START_SEC_VAR_CLEARED_BOOLEAN
  /* VAR_CLEARED_BOOLEAN pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_CLEARED_BOOLEAN
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_CLEARED_BOOLEAN           
#elif defined BSWM_STOP_SEC_VAR_CLEARED_BOOLEAN      
  /* VAR_CLEARED_BOOLEAN pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_CLEARED_BOOLEAN
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_CLEARED_BOOLEAN             
#elif defined BSWM_START_SEC_VAR_CLEARED_UNSPECIFIED
  /* VAR_CLEARED_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_CLEARED_UNSPECIFIED           
#elif defined BSWM_STOP_SEC_VAR_CLEARED_UNSPECIFIED      
  /* VAR_CLEARED_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_CLEARED_UNSPECIFIED             
#elif defined BSWM_START_SEC_VAR_INIT_16
  /* VAR_INIT_16 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_INIT_16
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_INIT_16           
#elif defined BSWM_STOP_SEC_VAR_INIT_16      
  /* VAR_INIT_16 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_INIT_16
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_INIT_16             
#elif defined BSWM_START_SEC_VAR_INIT_8
  /* VAR_INIT_8 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_INIT_8
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_INIT_8           
#elif defined BSWM_STOP_SEC_VAR_INIT_8      
  /* VAR_INIT_8 pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_INIT_8
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_INIT_8             
#elif defined BSWM_START_SEC_VAR_INIT_BOOLEAN
  /* VAR_INIT_BOOLEAN pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_INIT_BOOLEAN
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_INIT_BOOLEAN           
#elif defined BSWM_STOP_SEC_VAR_INIT_BOOLEAN      
  /* VAR_INIT_BOOLEAN pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_INIT_BOOLEAN
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_INIT_BOOLEAN             
#elif defined BSWM_START_SEC_VAR_INIT_UNSPECIFIED
  /* VAR_INIT_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_INIT_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_INIT_UNSPECIFIED           
#elif defined BSWM_STOP_SEC_VAR_INIT_UNSPECIFIED      
  /* VAR_INIT_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_INIT_UNSPECIFIED             
#elif defined BSWM_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  /* VAR_SAVED_ZONE_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED           
#elif defined BSWM_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED      
  /* VAR_SAVED_ZONE_UNSPECIFIED pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
  #include "Bsw_MemMap.h"
			 
  #undef BSWM_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED             
#elif defined BswM_START_SEC_CODE
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef BswM_START_SEC_CODE           
#elif defined BswM_STOP_SEC_CODE      
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef BswM_STOP_SEC_CODE             
#else 
#error "BswM_MemMap.h, wrong pragma command" 
#endif
