/*******************************************************************************
 * Autogenerated by MCALgen for MCU V3.0.51.35438: Mcu_Internal.h
 *******************************************************************************/
#ifndef MCU_INTERNAL_H_
#define MCU_INTERNAL_H_

extern const Mcu_ConfigType* Mcu_GetInternalConfig(void);

#endif /* MCU_INTERNAL_H_ */

