/** @file     Rte_Cfg.h
  *
  * @brief    RTE Configuration file
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.2.0
  *
  * @date     Thu Feb 15 15:55:09 2024
  */

#ifndef RTE_CFG_H
#define RTE_CFG_H

#include <Std_Types.h>

/* BEGIN: VFB tracing definitions */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE                            (0)
#endif /* !RTE_VFB_TRACE */
/* END: VFB tracing definitions */

#endif /* !RTE_CFG_H */
