/*
 **********************************************************************************************************************
 *
 * COPYRIGHT (c) ETAS GmbH 2021, all rights reserved
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************
*/
#ifndef EA_PRV_HIDERTEAPI_H
#define EA_PRV_HIDERTEAPI_H
/*
 **********************************************************************************************************************
 * Includes
 **********************************************************************************************************************
 */
#include "Ea_Cfg.h"
/*
 **********************************************************************************************************************
 * Type definitions
 **********************************************************************************************************************
 */
#if (EA_PRESENT == 1)
# if (defined(EA_RB_RTE_USED) && (EA_RB_RTE_USED != FALSE))
/**
 * Definition of a compiler switch which controls hiding of public Ea APIs provided by RTE generator,
 * for details please see coding guidelines Rule BSW_ServiceRTE_002.
 */
#  define EA_RB_HIDE_RTEAPI
# endif
#endif /* EA_PRESENT */
// If RTE generator is NOT used then the Ea uses all public APIs and data types from Ea.h and not from header files
// generated by the RTE.
#include "Ea.h"


/**
 * If RTE generator is used then the Ea uses all public APIs from header files generated by the RTE
 * and not from Ea.h.
 */
#ifdef EA_RB_HIDE_RTEAPI
# include "SchM_Ea.h"
#endif

/* EA_PRV_HIDERTEAPI_H */
#endif

