/*
 **********************************************************************************************************************
 *
 * Copyright (c) ETAS GmbH 2023, all rights reserved.
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 **********************************************************************************************************************
 
 **********************************************************************************************************************
 Machine Type: MCU_RB_GENERIC
 Generated by MEMMAPGEN 12.2.0  
 **********************************************************************************************************************
*/ 
/* MR12 DIR 4.10 VIOLATION: Memmap file must be included multiple times */
/* MR12 RULE 20.5 VIOLATION: AUTOSAR MemMap concept requires #undef, AUTOSAR MemMap requirements are incompatible to MISRA */ 
#if defined BFX_START_SEC_CODE
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef BFX_START_SEC_CODE           
#elif defined BFX_STOP_SEC_CODE      
  /* CODE pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CODE
  #include "Bsw_MemMap.h"
			 
  #undef BFX_STOP_SEC_CODE             
#elif defined BFX_START_SEC_CODE_FAST
  /* CODE_FAST pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CODE_FAST
  #include "Bsw_MemMap.h"
			 
  #undef BFX_START_SEC_CODE_FAST           
#elif defined BFX_STOP_SEC_CODE_FAST      
  /* CODE_FAST pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CODE_FAST
  #include "Bsw_MemMap.h"
			 
  #undef BFX_STOP_SEC_CODE_FAST             
#elif defined BFX_START_SEC_CODE_SLOW
  /* CODE_SLOW pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_START_SEC_CODE_SLOW
  #include "Bsw_MemMap.h"
			 
  #undef BFX_START_SEC_CODE_SLOW           
#elif defined BFX_STOP_SEC_CODE_SLOW      
  /* CODE_SLOW pragma configuration not available, please update the respective template file */ 
			 
  #define BSW_STOP_SEC_CODE_SLOW
  #include "Bsw_MemMap.h"
			 
  #undef BFX_STOP_SEC_CODE_SLOW             
#else 
#error "Bfx_MemMap.h, wrong pragma command" 
#endif
