/*******************************************************************************
 * Autogenerated by MCALgen for CAN V3.0.51.35438: Can_PBcfg.c
 *******************************************************************************/
/* [$CAN 78]  */
 /* [$Satisfies $CAN 1003] */
 /* [$Satisfies $CAN 1004] */

/************************************************************************************************************
 *                              Include Files
 ***********************************************************************************************************/
#include "Can_PBcfg.h"
/* [$CAN 111]  [$CAN 1012] */
/* Version checks */
#if (CAN_AR_RELEASE_MAJOR_VERSION != (4U)) || (CAN_AR_RELEASE_MINOR_VERSION != (8U)) || (CAN_AR_RELEASE_REVISION_VERSION != (0U))
 #error "CAN AUTOSAR version in CAN.h does not match 4.8.0"
#endif
#if (CAN_SW_MAJOR_VERSION != (3U)) || (CAN_SW_MINOR_VERSION != (0U)) || (CAN_SW_PATCH_VERSION != (51U))
 #error "CAN software version in CAN.h does not match 3.0.51"
#endif
#if (CAN_VENDOR_ID !=  (11U))
 #error "CAN Vendor ID in CAN.h does not match 11"
#endif

#define Can_DefaultBaudrateRef (0)

#define Can_DefaultFilterMask (0)

/* [$CAN 394]  */
/*----------------------------
 * Start of const
 *----------------------------*/
#define CAN_START_SEC_CONST_UNSPECIFIED
#include "Can_MemMap.h"

// Controller baudrates 
// Controller 0
#define Can_Can_Network_CANNODE_0_BR_0_0 (0)


static const Can_ControllerFdbaudrateConfigType  Can_Can_Network_CANNODE_0_FdBaudrateConfig_0[] = {
{800U, 0U, 10U, 0U, 0U, 0U, 0U, TRUE}
};
/* [$CAN 9387] [$CAN21 9387] [$CAN 9316] [$CAN21 9316] [$CAN 95] [$CAN21 905] [$CAN 973] [$CAN21 973] [$CAN 974] [$CAN21 974] [$CAN 975] [$CAN21 975] [$CAN 9383] [$CAN21 9383] */
/* [$CAN 1083] [$CAN 1084] [$CAN 1085] [$CAN 1086] [$CAN 1217] [$CAN21 9471] */
static const Can_ControllerBaudrateConfigType  Can_Can_Network_CANNODE_0_BaudrateConfig[] = {
  {500U, 1U, 0U, 10U, 0U, 0U, Can_Can_Network_CANNODE_0_FdBaudrateConfig_0}
};
static const Can_Hwp_HwFilter Can_HwFilters_Can_Network_CANNODE_0_Rx_Std_MailBox_1[] = {
  {20U, 2047}
};
static const Can_Hwp_RxHwObject Can_RxObjects_Can_Network_CANNODE_0[] = {
  {CanConf_CanHardwareObject_Can_Network_CANNODE_0_Rx_Std_MailBox_1, CAN_HWP_RXTYPE_FULL, CAN_HWP_IDTYPE_STANDARD, 1, Can_HwFilters_Can_Network_CANNODE_0_Rx_Std_MailBox_1, CAN_OBJECT_PL_8}
};

static const Can_Hwp_TxHwObject Can_TxObjects_Can_Network_CANNODE_0[] = {
  {CanConf_CanHardwareObject_Can_Network_CANNODE_0_Tx_Std_MailBox_1, 0, CAN_OBJECT_PL_8}
};

/* [$CAN 9323] [$CAN21 9323] [$CAN 965] [$CAN21 965] [$CAN 9325] [$CAN 1090] [$CAN 9326] [$CAN21 9326] [$CAN 9327] [$CAN21 9327] */
static const Can_Hwp_ChannelConfig Can_HwobjConfig_Can_Network_CANNODE_0 = {
  FALSE, /* [$CAN 278]  */
  FALSE, /* [$CAN 432]  */
  Can_RxObjects_Can_Network_CANNODE_0,
  1U,
  Can_TxObjects_Can_Network_CANNODE_0,
  1U
};
static const boolean Can_HwObjUsesPolling[2] = {
  FALSE,
  FALSE
};

static const uint16 Can_RxObjectIdToControllerIndex[1] = {
  0
};

static const uint16 Can_TxObjectIdToControllerIndex[2] = {
  CAN_NO_CONTROLLER_INDEX,
  0
};

/* [$CAN 9314] [$CAN21 9314] [$CAN 9316] [$CAN21 9316] [$CAN 9317] [$CAN21 9317] [$CAN 9318] [$CAN21 9318] [$CAN 9319] [$CAN21 9319] [$CAN 9330] [$CAN21 9330] [$CAN 9435] [$CAN21 9435] [$CAN 9359] [$CAN21 9359] */
/* [$CAN 1076] [$CAN 1077] [$CAN 1078] [$CAN 1079] [$CAN 1072] [$CAN 1081] [$CAN 1081] [$CAN 1082] */
static const Can_ControllerConfigType Can_ControllerConfig[] = {
  {CanConf_CanController_Can_Network_CANNODE_0, FALSE, CAN_POLLING, CAN_POLLING, CAN_POLLING, CAN_POLLING, 0U, Can_Can_Network_CANNODE_0_BR_0_0, 1U, Can_Can_Network_CANNODE_0_BaudrateConfig, 0, 0, 0, 0, &Can_HwobjConfig_Can_Network_CANNODE_0}
};



/* [$CAN 9327] [$CAN21 9327] [$CAN21 9489] */
Can_ConfigType Can_ConfigData = {
  Can_ControllerConfig, 1U, Can_RxObjectIdToControllerIndex, 1U, Can_TxObjectIdToControllerIndex, 2U, Can_HwObjUsesPolling, NULL_PTR /* [$CAN 1065] [$CAN 9434] [$CAN21 9434] */
};


/*----------------------------
 * End of const
 *----------------------------*/
#define CAN_STOP_SEC_CONST_UNSPECIFIED
#include "Can_MemMap.h"


