/** @file     Rte_Cbk.h
  *
  * @brief    RTE generated callbacks
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.2.0
  *
  * @date     Thu Feb  8 15:40:06 2024
  */

#ifndef RTE_CBK_H
#define RTE_CBK_H

#include "Rte_Type.h"
/* ----- RTE Callback functions ----- */

#define RTE_SIG_S_TESTECU_TO_APPLICATIONECU_DATA_CAN_NETWORK_CHANNEL_CAN_RX_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(void, RTE_CODE) Rte_COMCbk_S_TestECU_To_ApplicationECU_Data_Can_Network_Channel_CAN_Rx(void);
#define RTE_SIG_S_TESTECU_TO_APPLICATIONECU_DATA_CAN_NETWORK_CHANNEL_CAN_RX_STOP_SEC_CODE
#include "Rte_MemMap.h"

#endif /* !RTE_CBK_H */
