/** @file     Rte_ComM_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.2.0
  *
  * @date     Thu Feb  8 15:40:06 2024
  */

#ifndef RTE_ComM_TYPE_H
#define RTE_ComM_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#ifndef RTE_CORE
#define ComM_boolean_App_LowerLimit              ((ComM_bool_Impl)0)
#define ComM_boolean_App_UpperLimit              ((ComM_bool_Impl)255)
#define ComM_uint32_App_LowerLimit               ((ComM_uint32_Impl)0)
#define ComM_uint32_App_UpperLimit               ((ComM_uint32_Impl)4294967295)
#define ComM_uint8_App_LowerLimit                ((ComM_uint8_Impl)0)
#define ComM_uint8_App_UpperLimit                ((ComM_uint8_Impl)255)
#define ComM_unit16_App_LowerLimit               ((ComM_uint16_Impl)0)
#define ComM_unit16_App_UpperLimit               ((ComM_uint16_Impl)65535)
#endif /* RTE_CORE */

/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ComM_TYPE_H */
