/** @file     SchM_Bfx.h
  *
  * @brief    Basic Software Scheduler Module Interlink header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.2.0
  *
  * @date     Thu Feb  8 15:40:06 2024
  */

#ifndef SchM_Bfx
#define SchM_Bfx

#include "SchM_Bfx_Type.h"
#include "Rte_Intl.h"
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Schedulable Entity Prototypes
 ***
 *******************************************************/


#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !SchM_Bfx */
